import json

with open('config.json', 'r') as f:
    config_data = json.load(f)


APP_NAME = config_data["APP_NAME"]
APP_VERSION = config_data["APP_VERSION"]
CONTACT_EMAIL = config_data["CONTACT_DETAILS"]["EMAIL"]
CONTACT_PHONE = config_data["CONTACT_DETAILS"]["PHONE"]
CONTACT_ADDRESS = config_data["CONTACT_DETAILS"]["ADDRESS"]
CONTACT_WEBSITE = config_data["CONTACT_DETAILS"]["WEBSITE"]
APP_TIMEZONE = config_data["APP_TIMEZONE"]
ADMIN_EMAIL = config_data["ADMIN_USER_CONTACT_DETAILS"]["EMAIL"]
ADMIN_PHONE = config_data["ADMIN_USER_CONTACT_DETAILS"]["PHONE"]
ADMIN_ADDRESS = config_data["ADMIN_USER_CONTACT_DETAILS"]["ADDRESS"]
ADMIN_WEBSITE = config_data["ADMIN_USER_CONTACT_DETAILS"]["WEBSITE"]
REDDIT_USER_AGENT = config_data["REDDIT"]["REDDIT_USER_AGENT"]
WOLFRAM_APP_ID = config_data["WOLFRAM"]["WOLFRAM_APP_ID"]
JWT_ALGORITHM = config_data["JWT"]["JWT_ALGORITHM"]
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = config_data["JWT"]["JWT_ACCESS_TOKEN_EXPIRE_MINUTES"]
VOICE_ID = config_data["ELEVEN_LABS"]["VOICE_ID"]
DEBUG_MODE = config_data["DEBUG_MODE"]
LOGGING_LEVEL = config_data["LOGGING"]["LEVEL"]
LOGGING_FILE = config_data["LOGGING"]["FILE"]

SUPER_ADMIN_EMAIL = config_data["SUPER_ADMIN"]["EMAIL"]
SUPER_ADMIN_PASSWORD = config_data["SUPER_ADMIN"]["PASSWORD"]
SUPER_ADMIN_FIRSTNAME = config_data["SUPER_ADMIN"]["FIRST_NAME"]
SUPER_ADMIN_LASTNAME = config_data["SUPER_ADMIN"]["LAST_NAME"]
LOCAL_STORAGE_LOCATION = config_data["LOCAL_STORAGE_LOCATION"]

